/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dinosaur_Dinosaur */

#ifndef _Included_dinosaur_Dinosaur
#define _Included_dinosaur_Dinosaur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dinosaur_Dinosaur
 * Method:    InitLibrary
 * Signature: ()[Ldinosaur/torrent_failure;
 */
JNIEXPORT jobjectArray JNICALL Java_dinosaur_Dinosaur_InitLibrary
  (JNIEnv *, jobject);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    ReleaseLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dinosaur_Dinosaur_ReleaseLibrary
  (JNIEnv *, jobject);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    OpenMetafile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jobject JNICALL Java_dinosaur_Dinosaur_OpenMetafile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    AddTorrent
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dinosaur_Dinosaur_AddTorrent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    StartTorrent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dinosaur_Dinosaur_StartTorrent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    StopTorrent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dinosaur_Dinosaur_StopTorrent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    PauseTorrent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dinosaur_Dinosaur_PauseTorrent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    ContinueTorrent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dinosaur_Dinosaur_ContinueTorrent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    CheckTorrent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dinosaur_Dinosaur_CheckTorrent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    DeleteTorrent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dinosaur_Dinosaur_DeleteTorrent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    test
 * Signature: ()Ldinosaur/torrent_failure;
 */
JNIEXPORT jobject JNICALL Java_dinosaur_Dinosaur_test
  (JNIEnv *, jobject);

/*
 * Class:     dinosaur_Dinosaur
 * Method:    test2
 * Signature: ()[Ldinosaur/torrent_failure;
 */
JNIEXPORT jobjectArray JNICALL Java_dinosaur_Dinosaur_test2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
