package dinosaur;

public class DinosaurException extends Throwable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public enum ERR_CODES
	{
		NO_ERROR,
		ERR_CODE_NULL_REF,
		ERR_CODE_UNDEF,
		ERR_CODE_INVALID_FORMAT,
		ERR_CODE_NO_MEMORY_AVAILABLE,
		ERR_CODE_CAN_NOT_CREATE_THREAD,

		ERR_CODE_SOCKET_CLOSED,
		ERR_CODE_SOCKET_CAN_NOT_SEND,
		ERR_CODE_CAN_NOT_RESOLVE,

		ERR_CODE_INVALID_METAFILE,
		ERR_CODE_INVALID_ANNOUNCE,
		ERR_CODE_LEECHER_REJECTED,
		ERR_CODE_SEED_REJECTED,
		ERR_CODE_INVALID_FILE_INDEX,
		ERR_CODE_FAIL_SET_FILE_PRIORITY,
		ERR_CODE_BLOCK_TOO_BIG,

		ERR_CODE_CAN_NOT_INIT_FILES,
		ERR_CODE_FILE_NOT_EXISTS,
		ERR_CODE_FILE_NOT_OPENED,
		ERR_CODE_FILE_WRITE_OFFSET_OVERFLOW,

		ERR_CODE_DINOSAUR_INIT_ERROR,
		ERR_CODE_TORRENT_EXISTS,
		ERR_CODE_TORRENT_NOT_EXISTS,
		ERR_CODE_STATE_FILE_ERROR,

		ERR_CODE_INVALID_OPERATION,

		ERR_CODE_LRU_CACHE_NE,
		ERR_CODE_CACHE_FULL,

		ERR_CODE_BENCODE_PARSE_ERROR,
		ERR_CODE_BENCODE_ENCODE_ERROR,

		ERR_CODE_CAN_NOT_SAVE_CONFIG,
		ERR_CODE_DIR_NOT_EXISTS,
		ERR_CODE_INVALID_W_CACHE_SIZE,
		ERR_CODE_INVALID_R_CACHE_SIZE,
		ERR_CODE_INVALID_TRACKER_DEF_INTERVAL,
		ERR_CODE_INVALID_MAX_ACTIVE_SEEDS,
		ERR_CODE_INVALID_MAX_ACTIVE_LEECHS,
		ERR_CODE_INVALID_LISTEN_ON,
		ERR_CODE_INVALID_MAX_ACTIVE_TORRENTS,
	};
	public ERR_CODES err_code;
	public DinosaurException(int err_code)
	{
		this.err_code = ERR_CODES.values()[err_code];
	}
}
